# Generated by Django 3.2.9 on 2021-11-20 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_mood_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
