# Generated by Django 3.2.9 on 2021-11-20 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0005_auto_20211120_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodboard',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
