# Generated by Django 3.2.9 on 2021-11-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_moodboard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='created_by',
        ),
    ]
